In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/MachineLearning/master/dataset/Video%20Game%20Sales%20with%20Ratings/Video_Games_Sales_as_at_22_Dec_2016.csv")
dataset.head()

Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0   
1     29.08      3.58      6.81         0.77         40.24           NaN   
2     15.68     12.76      3.79         3.29         35.52          82.0   
3     15.61     10.93      3.28         2.95         32.77          80.0   
4     11.27      8.89     10.22         1.00         31.37           NaN   

   Critic_Count User_Score  User_Count Developer Rating  
0          51.0          8       322.0  Nintendo      E  
1           NaN        NaN         NaN       NaN    NaN  
2          73.0        8.3       709.0  Nintendo      E  
3          73.0          8       192.0  Nintendo      E  
4           NaN        NaN         NaN       NaN    NaN

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             16717 non-null  object 
 1   Platform         16719 non-null  object 
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object 
 4   Publisher        16665 non-null  object 
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object 
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object 
 15  Rating           9950 non-null   object 
dtypes: float64(9), object(7)
memory usage: 2.0+ MB


In [4]:
dataset = dataset.drop('Other_Sales', axis = 1) # apaga a coluna
dataset = dataset.drop('Global_Sales', axis = 1) # apaga a coluna
dataset = dataset.drop('Developer', axis = 1) # apaga a coluna
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             16717 non-null  object 
 1   Platform         16719 non-null  object 
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object 
 4   Publisher        16665 non-null  object 
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   Critic_Count     8137 non-null   float64
 10  User_Score       10015 non-null  object 
 11  User_Count       7590 non-null   float64
 12  Rating           9950 non-null   object 
dtypes: float64(7), object(6)
memory usage: 1.7+ MB


In [5]:
dataset = dataset.dropna(axis = 0) # apagar por linha
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6825 entries, 0 to 16706
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             6825 non-null   object 
 1   Platform         6825 non-null   object 
 2   Year_of_Release  6825 non-null   float64
 3   Genre            6825 non-null   object 
 4   Publisher        6825 non-null   object 
 5   NA_Sales         6825 non-null   float64
 6   EU_Sales         6825 non-null   float64
 7   JP_Sales         6825 non-null   float64
 8   Critic_Score     6825 non-null   float64
 9   Critic_Count     6825 non-null   float64
 10  User_Score       6825 non-null   object 
 11  User_Count       6825 non-null   float64
 12  Rating           6825 non-null   object 
dtypes: float64(7), object(6)
memory usage: 746.5+ KB


In [6]:
valores_menores_1 = dataset.loc[dataset['NA_Sales'] < 1]
valores_menores_1.head()

Name Platform  Year_of_Release         Genre  \
85          The Sims 3       PC           2009.0    Simulation   
94             FIFA 17      PS4           2016.0        Sports   
126            FIFA 14      PS3           2013.0        Sports   
138  World of Warcraft       PC           2004.0  Role-Playing   
143            FIFA 15      PS4           2014.0        Sports   

           Publisher  NA_Sales  EU_Sales  JP_Sales  Critic_Score  \
85   Electronic Arts      0.99      6.42      0.00          86.0   
94   Electronic Arts      0.66      5.75      0.08          85.0   
126  Electronic Arts      0.78      4.24      0.07          86.0   
138       Activision      0.08      6.21      0.00          93.0   
143  Electronic Arts      0.80      4.33      0.05          82.0   

     Critic_Count User_Score  User_Count Rating  
85           75.0        7.6       886.0      T  
94           41.0          5       398.0      E  
126          37.0        4.3       576.0      E  
138          57.0        7.3      2182.0      T  
143          47.0        5.7       988.0      E

In [7]:
dataset = dataset.loc[dataset['NA_Sales'] > 1]
dataset = dataset.loc[dataset['EU_Sales'] > 1]
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 636
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Name             258 non-null    object 
 1   Platform         258 non-null    object 
 2   Year_of_Release  258 non-null    float64
 3   Genre            258 non-null    object 
 4   Publisher        258 non-null    object 
 5   NA_Sales         258 non-null    float64
 6   EU_Sales         258 non-null    float64
 7   JP_Sales         258 non-null    float64
 8   Critic_Score     258 non-null    float64
 9   Critic_Count     258 non-null    float64
 10  User_Score       258 non-null    object 
 11  User_Count       258 non-null    float64
 12  Rating           258 non-null    object 
dtypes: float64(7), object(6)
memory usage: 28.2+ KB


In [8]:
nome_jogos = dataset['Name']
dataset = dataset.drop('Name', axis = 1) # Assim, vamos diminuir a variedade de dados
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 636
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Platform         258 non-null    object 
 1   Year_of_Release  258 non-null    float64
 2   Genre            258 non-null    object 
 3   Publisher        258 non-null    object 
 4   NA_Sales         258 non-null    float64
 5   EU_Sales         258 non-null    float64
 6   JP_Sales         258 non-null    float64
 7   Critic_Score     258 non-null    float64
 8   Critic_Count     258 non-null    float64
 9   User_Score       258 non-null    object 
 10  User_Count       258 non-null    float64
 11  Rating           258 non-null    object 
dtypes: float64(7), object(5)
memory usage: 26.2+ KB


In [9]:
from keras.layers import Dense, Dropout, Activation, Input
from keras.models import Model
previsores = dataset.iloc[:, [0,1,2,3,7,8,9,10,11]].values
previsores

array([['Wii', 2006.0, 'Sports', ..., '8', 322.0, 'E'],
       ['Wii', 2008.0, 'Racing', ..., '8.3', 709.0, 'E'],
       ['Wii', 2009.0, 'Sports', ..., '8', 192.0, 'E'],
       ...,
       ['Wii', 2007.0, 'Sports', ..., '8', 124.0, 'E10+'],
       ['PS2', 2001.0, 'Racing', ..., '7.9', 46.0, 'T'],
       ['PS2', 2003.0, 'Simulation', ..., '8.4', 42.0, 'T']], dtype=object)

In [10]:
vendas_na = dataset.iloc[:, 4].values
vendas_eu = dataset.iloc[:, 5].values
vendas_jp = dataset.iloc[:, 6].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
# Transformar colunas categóricas em numéricas

labelEncoder = LabelEncoder()

previsores[:, 0] = labelEncoder.fit_transform(previsores[:, 0]);
previsores[:, 2] = labelEncoder.fit_transform(previsores[:, 2]);
previsores[:, 3] = labelEncoder.fit_transform(previsores[:, 3]);
previsores[:, 8] = labelEncoder.fit_transform(previsores[:, 8]);
previsores

array([[10, 2006.0, 10, ..., '8', 322.0, 0],
       [10, 2008.0, 6, ..., '8.3', 709.0, 0],
       [10, 2009.0, 10, ..., '8', 192.0, 0],
       ...,
       [10, 2007.0, 10, ..., '8', 124.0, 1],
       [6, 2001.0, 6, ..., '7.9', 46.0, 3],
       [6, 2003.0, 9, ..., '8.4', 42.0, 3]], dtype=object)

In [11]:

column_transform = ColumnTransformer([("encoder", 
                         OneHotEncoder(), 
                        [0,2,3,8])],    
                       remainder = 'passthrough')


previsores = column_transform.fit_transform(previsores).toarray()
previsores

array([[  0. ,   0. ,   0. , ...,  51. ,   8. , 322. ],
       [  0. ,   0. ,   0. , ...,  73. ,   8.3, 709. ],
       [  0. ,   0. ,   0. , ...,  73. ,   8. , 192. ],
       ...,
       [  0. ,   0. ,   0. , ...,  47. ,   8. , 124. ],
       [  0. ,   0. ,   0. , ...,  15. ,   7.9,  46. ],
       [  0. ,   0. ,   0. , ...,  26. ,   8.4,  42. ]])

In [13]:
previsores.shape

(258, 61)

In [14]:
quantidade_saida = 3
quantidade_entrada = previsores.shape[1]
units = (quantidade_entrada + quantidade_saida) / 2
units

32.0

In [15]:

camada_entrada = Input(shape=(61,))

camada_oculta_1 = Dense(units = units, activation = 'sigmoid')(camada_entrada) # ligação entre as camadas
camada_oculta_2 = Dense(units = units, activation = 'sigmoid')(camada_oculta_1)

# Previsão de três saídas para as três regiões previstas
camada_saida_1 = Dense(units = 1, activation = 'linear')(camada_oculta_2)
camada_saida_2 = Dense(units = 1, activation = 'linear')(camada_oculta_2)
camada_saida_3 = Dense(units = 1, activation = 'linear')(camada_oculta_2)

regressor = Model(inputs = camada_entrada, 
                  outputs = [camada_saida_1, camada_saida_2, camada_saida_3])

regressor.compile(optimizer = 'adam', loss = 'mse')

regressor.fit(previsores, [vendas_na, vendas_eu, vendas_jp],
             epochs = 50, batch_size = 100)

Epoch 1/50
3/3 [==============================] - 0s 1ms/step - loss: 37.1314 - dense_2_loss: 25.0796 - dense_3_loss: 10.4792 - dense_4_loss: 1.5726
Epoch 2/50
3/3 [==============================] - 0s 1ms/step - loss: 36.0193 - dense_2_loss: 24.3564 - dense_3_loss: 10.1703 - dense_4_loss: 1.4926
Epoch 3/50
3/3 [==============================] - 0s 1ms/step - loss: 34.8800 - dense_2_loss: 23.5779 - dense_3_loss: 9.8718 - dense_4_loss: 1.4303
Epoch 4/50
3/3 [==============================] - 0s 2ms/step - loss: 33.8611 - dense_2_loss: 22.8887 - dense_3_loss: 9.5984 - dense_4_loss: 1.3739
Epoch 5/50
3/3 [==============================] - 0s 1ms/step - loss: 32.9264 - dense_2_loss: 22.2525 - dense_3_loss: 9.3472 - dense_4_loss: 1.3267
Epoch 6/50
3/3 [==============================] - 0s 2ms/step - loss: 31.9999 - dense_2_loss: 21.6107 - dense_3_loss: 9.0980 - dense_4_loss: 1.2912
Epoch 7/50
3/3 [==============================] - 0s 2ms/step - loss: 31.1326 - dense_2_loss: 21.0106 - dense_

In [16]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(previsores)
previsao_na[0:10]

array([[2.9441476],
       [2.9199512],
       [2.9441476],
       [2.9441476],
       [2.9441476],
       [2.9441473],
       [2.9441476],
       [2.9441476],
       [2.9441476],
       [2.9441476]], dtype=float32)

In [17]:
vendas_na[0:10]

array([41.36, 15.68, 15.61, 11.28, 13.96, 14.44,  9.71,  8.92, 15.  ,
        9.01])

In [18]:
features_final = np.column_stack((nome_jogos, vendas_na, previsao_na, vendas_eu, previsao_eu, vendas_jp, previsao_jp))
features_final

array([['Wii Sports', 41.36, 2.9441475868225098, ..., 2.2526893615722656,
        3.77, 0.656384289264679],
       ['Mario Kart Wii', 15.68, 2.9199512004852295, ...,
        2.2574777603149414, 3.79, 0.5935144424438477],
       ['Wii Sports Resort', 15.61, 2.9441475868225098, ...,
        2.2526893615722656, 3.28, 0.656384289264679],
       ...,
       ['Mario Strikers Charged', 1.05, 2.9441475868225098, ...,
        2.2526891231536865, 0.24, 0.6563843488693237],
       ['Crazy Taxi', 1.13, 2.9441475868225098, ..., 2.2526891231536865,
        0.06, 0.6563843488693237],
       ["The Sims: Bustin' Out", 1.07, 2.9441475868225098, ...,
        2.2526891231536865, 0.0, 0.6563843488693237]], dtype=object)

In [20]:
dataset_previsao = pd.DataFrame(data = features_final, 
                                columns = ['Names', 
                                           'NA_Sales',
                                           'NA_Sales_Predict',
                                           'EU_Sales',
                                           'EU_Sales_Predict',
                                           'JP_Sales',
                                           'JP_Sales_Predict'])
dataset_previsao.head(20)

Names NA_Sales NA_Sales_Predict  \
0                                     Wii Sports    41.36          2.94415   
1                                 Mario Kart Wii    15.68          2.91995   
2                              Wii Sports Resort    15.61          2.94415   
3                          New Super Mario Bros.    11.28          2.94415   
4                                       Wii Play    13.96          2.94415   
5                      New Super Mario Bros. Wii    14.44          2.94415   
6                                  Mario Kart DS     9.71          2.94415   
7                                        Wii Fit     8.92          2.94415   
8                             Kinect Adventures!       15          2.94415   
9                                   Wii Fit Plus     9.01          2.94415   
10                            Grand Theft Auto V     7.02          3.03644   
11  Brain Age: Train Your Brain in Minutes a Day     4.74          2.94415   
12                            Grand Theft Auto V     9.66          3.03644   
13                   Grand Theft Auto: Vice City     8.41          2.91983   
14   Brain Age 2: More Training in Minutes a Day     3.43          2.94415   
15                        Gran Turismo 3: A-Spec     6.85          2.94415   
16                Call of Duty: Modern Warfare 3     9.04          2.76878   
17                       Call of Duty: Black Ops      9.7          3.34425   
18                    Call of Duty: Black Ops II     4.99          3.12781   
19                    Call of Duty: Black Ops II     8.25           3.0243   

   EU_Sales EU_Sales_Predict JP_Sales JP_Sales_Predict  
0     28.96          2.25269     3.77         0.656384  
1     12.76          2.25748     3.79         0.593514  
2     10.93          2.25269     3.28         0.656384  
3      9.14          2.25269      6.5         0.656384  
4      9.18          2.25269     2.93         0.656384  
5      6.94          2.25269      4.7         0.656384  
6      7.47          2.25269     4.13         0.656384  
7      8.03          2.25269      3.6         0.656384  
8      4.89          2.25269     0.24         0.656384  
9      8.49          2.25269     2.53         0.656384  
10     9.09           2.2287     0.98         0.539235  
11      9.2          2.25269     4.16         0.656384  
12     5.14           2.2287     0.06         0.539235  
13     5.49          2.25747     0.47         0.593279  
14     5.35          2.25269     5.32         0.656384  
15     5.09          2.25269     1.87         0.656384  
16     4.24          2.13575     0.13         0.410675  
17     3.68          2.49969     0.11         0.508454  
18     5.73          2.41201     0.65         0.518047  
19     4.24          2.24052     0.07         0.474379